package com.aspose.jmap;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * One node of the Email's MIME {@code bodyStructure} tree.
 *
 * <p>All fields correspond directly to the JMAP wire format property names.
 * The class is immutable; use the package‑visible all‑args constructor
 * (generated by the code generator) to create instances.</p>
 */
public final class EmailBodyPart {
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final String partId;               // nullable
    private final String blobId;               // nullable, Id → String
    private final long size;                   // required, UnsignedInt
    private final List<EmailHeader> headers;   // required
    private final String name;                 // nullable
    private final String type;                 // required
    private final String charset;              // nullable
    private final String disposition;          // nullable
    private final String cid;                  // nullable
    private final List<String> language;       // nullable
    private final String location;             // nullable
    private final List<EmailBodyPart> subParts; // nullable

    // package‑visible all‑args constructor
    EmailBodyPart(
            String partId,
            String blobId,
            long size,
            List<EmailHeader> headers,
            String name,
            String type,
            String charset,
            String disposition,
            String cid,
            List<String> language,
            String location,
            List<EmailBodyPart> subParts) {
        this.partId = partId;
        this.blobId = blobId;
        this.size = size;
        this.headers = headers != null ? Collections.unmodifiableList(headers) : Collections.emptyList();
        this.name = name;
        this.type = type;
        this.charset = charset;
        this.disposition = disposition;
        this.cid = cid;
        this.language = language != null ? Collections.unmodifiableList(language) : null;
        this.location = location;
        this.subParts = subParts != null ? Collections.unmodifiableList(subParts) : null;
    }

    /** @return partId or {@code null} */
    public String getPartId() {
        return partId;
    }

    /** @return blobId or {@code null} */
    public String getBlobId() {
        return blobId;
    }

    /** @return size (unsigned integer) */
    public long getSize() {
        return size;
    }

    /** @return immutable list of headers (never {@code null}) */
    public List<EmailHeader> getHeaders() {
        return headers;
    }

    /** @return name (filename) or {@code null} */
    public String getName() {
        return name;
    }

    /** @return MIME type (e.g. {@code text/plain}) */
    public String getType() {
        return type;
    }

    /** @return charset or {@code null} */
    public String getCharset() {
        return charset;
    }

    /** @return disposition or {@code null} */
    public String getDisposition() {
        return disposition;
    }

    /** @return content‑Id or {@code null} */
    public String getCid() {
        return cid;
    }

    /** @return language list or {@code null} */
    public List<String> getLanguage() {
        return language;
    }

    /** @return location or {@code null} */
    public String getLocation() {
        return location;
    }

    /** @return sub‑parts list or {@code null} */
    public List<EmailBodyPart> getSubParts() {
        return subParts;
    }

    /**
     * Parses a {@link JsonNode} representing an {@code EmailBodyPart}.
     *
     * @param data JSON object node
     * @return an {@code EmailBodyPart} instance
     * @throws JmapProtocolError if required fields are missing or have invalid types
     */
    public static EmailBodyPart fromJson(JsonNode data) {
        if (data == null || !data.isObject()) {
            throw new JmapProtocolError("invalidArgument", "EmailBodyPart JSON must be an object");
        }

        String partId = getNullableText(data, "partId");
        String blobId = getNullableText(data, "blobId");

        JsonNode sizeNode = data.get("size");
        if (sizeNode == null || sizeNode.isNull() || !sizeNode.isNumber()) {
            throw new JmapProtocolError("invalidArgument", "Missing or invalid required field 'size'");
        }
        long size = sizeNode.asLong();

        JsonNode headersNode = data.get("headers");
        if (headersNode == null || !headersNode.isArray()) {
            throw new JmapProtocolError("invalidArgument", "Missing or invalid required field 'headers'");
        }
        List<EmailHeader> headers = new ArrayList<>();
        for (JsonNode h : headersNode) {
            headers.add(EmailHeader.fromJson(h));
        }

        String name = getNullableText(data, "name");
        String type = getRequiredText(data, "type");
        String charset = getNullableText(data, "charset");
        String disposition = getNullableText(data, "disposition");
        String cid = getNullableText(data, "cid");

        List<String> language = null;
        JsonNode langNode = data.get("language");
        if (langNode != null && langNode.isArray()) {
            language = new ArrayList<>();
            for (JsonNode l : langNode) {
                if (!l.isTextual()) {
                    throw new JmapProtocolError("invalidArgument", "Invalid language entry, expected string");
                }
                language.add(l.asText());
            }
        }

        String location = getNullableText(data, "location");

        List<EmailBodyPart> subParts = null;
        JsonNode subPartsNode = data.get("subParts");
        if (subPartsNode != null && subPartsNode.isArray()) {
            subParts = new ArrayList<>();
            for (JsonNode sp : subPartsNode) {
                subParts.add(EmailBodyPart.fromJson(sp));
            }
        }

        return new EmailBodyPart(
                partId,
                blobId,
                size,
                headers,
                name,
                type,
                charset,
                disposition,
                cid,
                language,
                location,
                subParts);
    }

    /**
     * Serialises this {@code EmailBodyPart} to a {@link JsonNode}.
     *
     * @return JSON representation adhering to the JMAP wire format
     */
    public JsonNode toJson() {
        ObjectNode obj = MAPPER.createObjectNode();

        if (partId != null) {
            obj.put("partId", partId);
        }
        if (blobId != null) {
            obj.put("blobId", blobId);
        }
        obj.put("size", size);

        ArrayNode headersArray = obj.putArray("headers");
        for (EmailHeader h : headers) {
            headersArray.add(h.toJson());
        }

        if (name != null) {
            obj.put("name", name);
        }
        obj.put("type", type);

        if (charset != null) {
            obj.put("charset", charset);
        }
        if (disposition != null) {
            obj.put("disposition", disposition);
        }
        if (cid != null) {
            obj.put("cid", cid);
        }
        if (language != null) {
            ArrayNode langArray = obj.putArray("language");
            for (String l : language) {
                langArray.add(l);
            }
        }
        if (location != null) {
            obj.put("location", location);
        }
        if (subParts != null) {
            ArrayNode subPartsArray = obj.putArray("subParts");
            for (EmailBodyPart sp : subParts) {
                subPartsArray.add(sp.toJson());
            }
        }

        return obj;
    }

    // -----------------------------------------------------------------------
    // Helper methods for extracting required/optional text fields
    // -----------------------------------------------------------------------

    private static String getNullableText(JsonNode node, String field) {
        JsonNode f = node.get(field);
        return (f != null && !f.isNull()) ? f.asText() : null;
    }

    private static String getRequiredText(JsonNode node, String field) {
        JsonNode f = node.get(field);
        if (f == null || f.isNull() || !f.isTextual()) {
            throw new JmapProtocolError("invalidArgument", "Missing or invalid required field '" + field + "'");
        }
        return f.asText();
    }
}
